import { MigrationInterface, QueryRunner } from "typeorm";

export class G1Auth1787128685232 implements MigrationInterface {
  name = "G1Auth1787128685232";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TYPE "status_user" AS ENUM ('ACTIVE', 'BANNED')`);

    await queryRunner.query(`
      CREATE TABLE "roles" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" varchar(50) NOT NULL UNIQUE,
        "description" varchar(255)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "permissions" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" varchar(100) NOT NULL UNIQUE,
        "description" varchar(255)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "role_id" bigint NOT NULL,
        "email" varchar(255) NOT NULL UNIQUE,
        "password_hash" varchar(255),
        "full_name" varchar(100) NOT NULL,
        "phone" varchar(20),
        "avatar" varchar(255),
        "date_of_birth" date,
        "address_detail" varchar(255),
        "ward_code" varchar(20),
        "status" "status_user" NOT NULL DEFAULT 'ACTIVE',
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "updated_at" timestamptz NOT NULL DEFAULT now(),
        "deleted_at" timestamptz,
        "last_login_at" timestamptz,
        "email_verified_at" timestamptz,
        CONSTRAINT "fk_users_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id"),
        CONSTRAINT "fk_users_ward" FOREIGN KEY ("ward_code") REFERENCES "wards"("code")
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_users_role_id" ON "users" ("role_id")`);
    await queryRunner.query(`CREATE INDEX "idx_users_status" ON "users" ("status")`);
    await queryRunner.query(`CREATE INDEX "idx_users_ward_code" ON "users" ("ward_code")`);

    await queryRunner.query(`
      CREATE TABLE "role_permissions" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "role_id" bigint NOT NULL,
        "permission_id" bigint NOT NULL,
        CONSTRAINT "fk_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE,
        CONSTRAINT "fk_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE,
        CONSTRAINT "uq_role_permissions" UNIQUE ("role_id", "permission_id")
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_role_permissions_role_id" ON "role_permissions" ("role_id")`);
    await queryRunner.query(`CREATE INDEX "idx_role_permissions_permission_id" ON "role_permissions" ("permission_id")`);

    await queryRunner.query(`
      CREATE TABLE "sessions" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" bigint NOT NULL,
        "refresh_token_hash" varchar(64) NOT NULL UNIQUE,
        "expires_at" timestamptz NOT NULL,
        "is_revoked" boolean NOT NULL DEFAULT false,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "fk_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "idx_sessions_user_id" ON "sessions" ("user_id")`);
    await queryRunner.query(`CREATE INDEX "idx_sessions_expires_at" ON "sessions" ("expires_at")`);

    await queryRunner.query(`
      CREATE TABLE "user_oauth_accounts" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" bigint NOT NULL,
        "provider" varchar(30) NOT NULL,
        "provider_user_id" varchar(255) NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT "fk_user_oauth_accounts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
        CONSTRAINT "uq_oauth_provider_account" UNIQUE ("provider", "provider_user_id"),
        CONSTRAINT "uq_user_oauth_provider" UNIQUE ("user_id", "provider")
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "user_oauth_accounts"`);
    await queryRunner.query(`DROP TABLE "sessions"`);
    await queryRunner.query(`DROP TABLE "role_permissions"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TABLE "permissions"`);
    await queryRunner.query(`DROP TABLE "roles"`);
    await queryRunner.query(`DROP TYPE "status_user"`);
  }
}
